CREATE TABLE IF NOT EXISTS SALRIES(
  NAMWE TEXT,
  SUM TEXT,
  AVERAGE TEXT,
  MINIMUM TEXT,
  MAXIMUM TEXT,
);

INSERT INTO SALRIES ( NAME, SUM, AVERAGE, MINIMUM, MAXIMUM) VALUES
('MAX', '100', '112', ' 2131', '1231')
('JOHN', '112' , '321, '13', '13)


SELECT * FROM SALRIES
